### ISSUE TITLE
Weird Unknown bug with itincheck_complete()

### ISSUE THREAD

**Issue by cca32** [adrianchang3/GDS_Scripts#10]
Not sure what exactly the bug is, but good to leave it as an issue here so we know if there are any outstanding TODO's / bugs to be fixed.

Use the label system on the right to either 
1) assign the work
2) label the work
3) attach a branch or PR to this issue
4) attach to a project/milestone if you ever wind up using those

Then in specific PR's you can link this issue to address this bug.

**Comment by cca32** [comment]
7cb5e765d951847bd3d4d7e2fa29e477fabf3a65 might be a potential solution worth testing
@adrianchang3

**Comment by adrianchang3** [comment]
this bug no longer exists but another issue exists with itincapcomplete.

itincap successful prints when successful. -> good
itincap failed prints when failed. -> good

itincap failed will keep printing every second and only timeout after 5 seconds -> intended, but bad
user clicks "close window" in GDS because error modal pops up -> user action
**if user clicks "close window" within 5 seconds, itincapcomplete will receive a "done" and print "Itin cap successful"**  ->> **this is the bug**

**Comment by adrianchang3** [comment]
no solution at the moment.

workaround is to remove itincapcomplete as it is now, and:

1. implement a time.sleep while itincap is running
2. check after time.sleep if itincapwindow is still open

This is a simple fix, but time.sleep is an arbitrary wait that is not efficient. It is possible for itincaps to persist longer than expected depending on the itinerary.

Would prefer a "hard-check" solution based on more absolute variables.

**Comment by adrianchang3** [comment]
![image](https://user-images.githubusercontent.com/60890504/209225185-6111e2d1-7a0f-4b23-8b0c-f4fa1382c137.png)

**Comment by adrianchang3** [comment]
Resolved PR:#14
